### ISSUE TITLE
Anaconda (conda-forge) 版リリースご承認のお願い

### ISSUE THREAD

**Issue by yu9824** [ciffelia/matplotlib-fontja#3]
突然のご連絡失礼致します。

PyPIに公開いただいている本パッケージをAnacondaでインストールができるようにさせていただきたいのですが、ご承認いただけますでしょうか。

ご承認いただける場合、PR (https://github.com/conda-forge/staged-recipes/pull/25540) に同意いただける旨をコメントいただくことは可能でしょうか。
> The following maintainers have not yet confirmed that they are willing to be listed here: ciffelia. Please ask them to comment on this PR if they are.

お忙しいところ大変恐縮です。
ご検討いただけますと幸いです。

何卒よろしくお願いいたします。

**Comment by ciffelia** [comment]
遅くなりました。問題ありません。

**Comment by yu9824** [comment]
ご承認ありがとうございます。
無事リリースされました。

https://anaconda.org/conda-forge/matplotlib-fontja
